server:
  port: 8081

spring:
  application:
    name: users-service

  r2dbc:
    url: ${R2DBC_URL:r2dbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 60000

auth:
  token:
    expiration: ${AUTH_TOKEN_EXPIRATION:60}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql: INFO